/* Optional proposed WebMCP API. The app has no dependency on browser support. */
(function(S){
 const context=document.modelContext;if(!context?.registerTool)return;
 const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
 const register=tool=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{/* Experimental API may be unavailable. */}};
 register({name:'list_species',title:'Read the local ecosystem',description:'Read illustrative reference and user-provided species snapshots. No live market data is queried.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:100}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input={}){if(typeof input!=='object'||input===null||input.query!==undefined&&typeof input.query!=='string')throw new Error('query must be a string');const query=(input.query||'').toLowerCase();return S.all().filter(s=>(s.ticker+' '+s.tokenName+' '+s.contractAddress).toLowerCase().includes(query)).map(s=>({id:s.id,ticker:s.ticker,generation:s.generation,health:s.health,status:s.status,marketCap:s.marketCap,source:s.demo?'illustrative-reference':'user-provided'}));}});
 register({name:'open_species_profile',title:'Open a species',description:'Navigate to an existing species profile, showing saved market DNA and evolution history.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!input||typeof input.id!=='string'||!S.find(input.id))throw new Error('Unknown species ID');location.hash='species/'+input.id;S.render();return {id:input.id,view:'species-profile'};}});
 register({name:'start_species_discovery',title:'Start local discovery',description:'Open the discovery form. This does not create or save a species; the user enters and submits the market snapshot.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(){document.querySelector('[data-discover]')?.click();if(!document.querySelector('#discover-form')){location.hash='ecosystem';S.render();document.querySelector('[data-discover]').click();}return {view:'discovery-form',saved:false};}});
})(window.SpeciesApp);
