/* Full-resolution local PNG export. No external images, image services or share attachment claims. */
(function(S){
 const types=['MY PNL','SPECIES STATUS','NEW EVOLUTION','ATH','MUTATION','SURVIVAL','RESURRECTION'];
 S.pnl=(species,position)=>{const percentage=(species.marketCap/position.entryMarketCap-1)*100;return {percentage,gain:position.sol*percentage/100,current:position.sol*(1+percentage/100)};};
 S.pnlText=p=>(p>=0?'+':'')+p.toFixed(1)+'%';
 const loadImage=src=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=src;});
 function wrap(ctx,text,x,y,maxWidth,lineHeight,maxLines=3){const words=text.split(' ');let line='',n=0;for(const w of words){const test=line+w+' ';if(ctx.measureText(test).width>maxWidth&&line){ctx.fillText(line.trim(),x,y+n*lineHeight);line=w+' ';n++;if(n>=maxLines)return;}else line=test;}ctx.fillText(line.trim(),x,y+n*lineHeight);}
 S.cards={types,async open(id,type='SPECIES STATUS'){const s=S.find(id);if(!s)return;const position=S.store.get().positions[id];if(type==='MY PNL'&&!position){this.position(id,()=>this.open(id,'MY PNL'));return;}const settings=S.store.get().cardSettings;let currentType=type,format=settings.format||'LANDSCAPE';S.modal(`<div class="eyebrow">SPECIMEN EXPORT / MARKET DNA</div><h2 class="modal-heading">YOUR BAG. YOUR SPECIES.</h2><div class="card-controls"><select id="card-type" aria-label="Card type">${types.map(t=>`<option ${t===type?'selected':''}>${t}</option>`).join('')}</select><select id="card-format" aria-label="Card format"><option ${format==='LANDSCAPE'?'selected':''}>LANDSCAPE</option><option ${format==='SQUARE'?'selected':''}>SQUARE</option></select><button class="button outline small" id="edit-position">EDIT POSITION</button></div><canvas id="export-canvas" class="card-preview" aria-label="Generated species card preview"></canvas><div class="card-controls"><button id="download-card" class="button">DOWNLOAD PNG ↓</button><button id="share-card" class="button outline">SHARE ON X ↗</button></div><p class="help">1. Download your card. 2. Open X with copy. Attach the downloaded PNG yourself.<br>Market-cap based PNL excludes fees, slippage and SOL/USD changes. No on-chain position is read.</p><p class="error-text" id="card-error" role="alert"></p>`);
 const canvas=document.querySelector('#export-canvas');let revision=0,ready=false;const update=async()=>{const current=++revision;ready=false;document.querySelector('#download-card').disabled=true;try{await this.draw(canvas,s,currentType,format);if(current!==revision||!canvas.isConnected)return;ready=true;document.querySelector('#download-card').disabled=false;S.store.save({cardSettings:{type:currentType,format}});}catch{if(current===revision&&canvas.isConnected)document.querySelector('#card-error').textContent='Unable to render this image. Try replacing the uploaded image.';}};
 document.querySelector('#card-type').onchange=ev=>{currentType=ev.target.value;if(currentType==='MY PNL'&&!S.store.get().positions[id]){this.position(id,()=>this.open(id,'MY PNL'));return;}update();};document.querySelector('#card-format').onchange=ev=>{format=ev.target.value;update();};document.querySelector('#edit-position').onclick=()=>this.position(id,()=>this.open(id,'MY PNL'));
 document.querySelector('#download-card').onclick=()=>{if(!ready)return;canvas.toBlob(blob=>{if(!blob){S.toast('Export failed. Please try again.');return;}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`SPECIES-${s.ticker}-${currentType.toLowerCase().replaceAll(' ','-')}-${format.toLowerCase()}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);S.toast('PNG downloaded. Ready for the timeline.');},'image/png');};document.querySelector('#share-card').onclick=()=>{const text=this.shareText(s,currentType);window.open('https://x.com/intent/tweet?text='+encodeURIComponent(text),'_blank','noopener,noreferrer');S.toast('X opens with copy. Attach your downloaded PNG.');};await update();},
 position(id,after){const s=S.find(id),p=S.store.get().positions[id]||{};S.modal(`<div class="eyebrow">MANUALLY ENTERED POSITION</div><h2 class="modal-heading">WHAT DID YOU HOLD?</h2><p class="modal-intro">Current ${s.demo?'illustrative reference':'saved'} market cap: ${S.money(s.marketCap,true)}. Your position stays on this device.</p><form id="position-form"><div class="form-grid"><label>ENTRY MARKET CAP (USD)<input name="entryMarketCap" type="number" min="0.01" max="1000000000000000" step="any" value="${p.entryMarketCap||''}" placeholder="18400" required></label><label>POSITION SIZE (SOL)<input name="sol" type="number" min="0.000001" max="1000000000" step="any" value="${p.sol||''}" placeholder="2.4" required></label><label class="full">ENTRY PRICE (OPTIONAL, USD)<input name="entryPrice" type="number" min="0" step="any" value="${p.entryPrice||''}" placeholder="For your records"></label></div><p class="help">Approximate PNL = (current MC ÷ entry MC − 1) × 100. Assumes unchanged token supply. Entry price is saved for your records.</p><button class="button" type="submit">SAVE POSITION & GENERATE CARD ↗</button></form>`);document.querySelector('#position-form').onsubmit=ev=>{ev.preventDefault();const d=Object.fromEntries(new FormData(ev.target));const pos={entryMarketCap:+d.entryMarketCap,sol:+d.sol,entryPrice:d.entryPrice?+d.entryPrice:null};if(!Number.isFinite(pos.entryMarketCap)||pos.entryMarketCap<=0||!Number.isFinite(pos.sol)||pos.sol<=0)return;const state=S.store.get();if(S.store.save({positions:{...state.positions,[id]:pos}})){S.store.activity(`Position recorded for $${s.ticker}.`);after?.();}};},
 shareText(s,type){const pos=S.store.get().positions[s.id];if(type==='MY PNL'&&pos){const pnl=S.pnl(s,pos).percentage;return pnl<0?`Apparently my $${s.ticker} is critically injured.\n\n${S.pnlText(pnl)} PNL. Still alive somehow.\nGEN ${S.roman(s.generation)} · ${s.health}% health\n\nThe market is its DNA. $SPECIES\nManually entered position · Estimated PNL.`:`My $${s.ticker} evolved to GEN ${S.roman(s.generation)}.\n\n${S.pnlText(pnl)} PNL.\n${s.primaryTrait} trait unlocked.\n\nThe market is its DNA. $SPECIES\nManually entered position · Estimated PNL.`;}return `${type==='SPECIES STATUS'?'LIFE DETECTED.':type+' DETECTED.'}\n\n$${s.ticker} · GEN ${S.roman(s.generation)}\n${s.primaryTrait} · ${s.health}% health\n\nThe market is its DNA. $SPECIES\nIllustrative reference or saved market snapshot.`;},
 async draw(canvas,s,type,format){const square=format==='SQUARE',w=square?1080:1200,h=square?1080:675;canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');const pos=S.store.get().positions[s.id],pnl=type==='MY PNL'&&pos?S.pnl(s,pos):null,negative=pnl&&pnl.percentage<0;const accent=negative?'#e99883':'#c1f55a';const [art,logo,source,wordmark]=await Promise.all([loadImage(s.speciesImage),loadImage('assets/logo/logo-new.jpg'),!s.customArt&&s.originalImage?.startsWith('data:')?loadImage(s.originalImage):Promise.resolve(null),loadImage('assets/logo/type.svg')]);
 ctx.fillStyle='#10150e';ctx.fillRect(0,0,w,h);const glow=ctx.createRadialGradient(w*.77,h*.5,10,w*.77,h*.5,w*.5);glow.addColorStop(0,negative?'#3c241d':'#2b3c1c');glow.addColorStop(1,'#10150e');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);ctx.strokeStyle='#8f9e6b12';ctx.lineWidth=1;for(let x=0;x<w;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}for(let y=0;y<h;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}ctx.strokeStyle='#435533';ctx.strokeRect(20,20,w-40,h-40);ctx.save();ctx.globalCompositeOperation='screen';ctx.drawImage(logo,44,36,58,58);ctx.restore();ctx.fillStyle='#f0f1e8';ctx.drawImage(wordmark,103,48,147,32);ctx.font='12px monospace';ctx.fillStyle='#a5b28e';ctx.textAlign='right';ctx.fillText(`SPECIMEN #${String(s.number).padStart(5,'0')} / GEN ${S.roman(s.generation)}`,w-50,70);ctx.textAlign='left';
 const label=pnl?(negative?'CRITICALLY INJURED':s.extinctionEventsSurvived>=3&&pnl.percentage<300?'SURVIVOR':'APEX HOLDER'):{'SPECIES STATUS':'LIFE DETECTED','NEW EVOLUTION':'SPECIES EVOLVED','ATH':'ALL-TIME HIGH / SNAPSHOT','MUTATION':'MUTATION DETECTED','SURVIVAL':'REFUSES TO DIE','RESURRECTION':'LIFE DETECTED. AGAIN.'}[type];ctx.fillStyle=accent;ctx.font='bold 16px monospace';ctx.fillText(label,53,139);ctx.fillStyle='#f0f1e8';ctx.font='900 68px Arial';ctx.fillText('$'+s.ticker,48,219);ctx.fillStyle='#a8b795';ctx.font='14px monospace';wrap(ctx,s.tokenName+' / '+s.scientificName.toUpperCase(),52,249,square?870:560,22,2);
 const artSize=square?470:500,ax=square?540:690,ay=square?316:120;ctx.globalAlpha=.95;ctx.drawImage(art,ax,ay,artSize,artSize);ctx.globalAlpha=1;if(source){ctx.save();ctx.beginPath();ctx.arc(ax+artSize*.51,ay+artSize*.51,artSize*.13,0,Math.PI*2);ctx.clip();ctx.filter='sepia(.5) hue-rotate(25deg) contrast(1.2)';ctx.drawImage(source,ax+artSize*.38,ay+artSize*.38,artSize*.26,artSize*.26);ctx.restore();ctx.strokeStyle=accent;ctx.beginPath();ctx.arc(ax+artSize*.51,ay+artSize*.51,artSize*.14,0,Math.PI*2);ctx.stroke();}
 const value=pnl?S.pnlText(pnl.percentage):s.health+'%';ctx.fillStyle=accent;ctx.font=`900 ${value.length>8?83:104}px Arial`;ctx.fillText(value,45,390);ctx.font='12px monospace';ctx.fillStyle='#a5b28e';ctx.fillText(pnl?'APPROXIMATE PNL':'SPECIES HEALTH',52,414);
 const fields=pnl?[['ENTRY MC',S.money(pos.entryMarketCap)],['CURRENT MC',S.money(s.marketCap)],['POSITION',pos.sol.toFixed(3).replace(/0+$/,'').replace(/\.$/,'')+' SOL'],['HEALTH',s.health+'%']]:[['MARKET CAP',S.money(s.marketCap)],['ATH',S.money(s.athMarketCap)],['HOLDERS',s.holders.toLocaleString('en-US')],['24H VOLUME',S.money(s.volume24h)]];const cols=square?2:4;fields.forEach(([label,v],i)=>{const x=52+(i%cols)*(square?235:157),y=(square?487:467)+Math.floor(i/cols)*80;ctx.font='11px monospace';ctx.fillStyle='#849376';ctx.fillText(label,x,y);ctx.font='bold 21px monospace';ctx.fillStyle='#e4e9dc';ctx.fillText(v,x,y+30);});
 const bottomY=square?740:553;ctx.font='bold 13px monospace';ctx.fillStyle=accent;ctx.fillText('TRAIT / '+(negative?'STILL FUCKING HERE':s.primaryTrait),52,bottomY);ctx.fillStyle='#849376';ctx.font='12px monospace';ctx.fillText(`GEN ${S.roman(s.generation)} · ${s.mutationCount} MUTATIONS · ${s.extinctionEventsSurvived} EXTINCTION EVENTS SURVIVED`,52,bottomY+26);if(square){ctx.fillText('SPECIES HEALTH '+s.health+'% · '+s.status,52,bottomY+52);ctx.fillText('EVOLUTIONS WITNESSED '+s.evolutionHistory.filter(e=>e.event.startsWith('GEN')).length,52,bottomY+78);}
 const progressY=square?870:603;ctx.fillStyle='#34432a';ctx.fillRect(52,progressY,w-104,4);ctx.fillStyle=accent;ctx.fillRect(52,progressY,(w-104)*s.evolutionProgress/100,4);ctx.fillStyle='#9dac8b';ctx.font='11px monospace';ctx.fillText(`EVOLUTION ${s.evolutionProgress}% / NEXT ${S.money(s.nextEvolutionRequirement)} MC`,52,progressY+24);ctx.fillStyle='#f0f1e8';ctx.font='bold 14px monospace';ctx.fillText('THE MARKET IS ITS DNA.',52,h-33);ctx.textAlign='right';ctx.fillStyle='#738666';ctx.font='10px monospace';ctx.fillText(s.demo?'ILLUSTRATIVE REFERENCE SNAPSHOT':'SAVED MARKET SNAPSHOT',w-52,h-33);ctx.textAlign='left';}
 };
})(window.SpeciesApp);
