/* All generation and market-change rules live here. No random or remote market inputs. */
(function(S){
 const thresholds={generations:[0,100000,1000000,100000000,1000000000,2000000000,5000000000,10000000000,20000000000,50000000000],socialHolders:1000,metabolismRatio:.2,mutationDrawdown:.65,ancientDays:730,dormantRatio:.005,criticalHealth:20,extinctionDays:14};
 S.evolution={thresholds,analyze(input,previous=null){
 const seed=S.hash(input.contractAddress.trim().toLowerCase()+'|'+input.ticker.toUpperCase());const mc=+input.marketCap,ath=Math.max(+input.athMarketCap,mc),volume=+input.volume24h,age=+input.age,holders=+input.holders;const drawdown=ath?1-mc/ath:0;const ratio=mc?volume/mc:0;const inactive=volume===0;
 let generation=Math.max(1,thresholds.generations.filter(t=>mc>=t).length);generation=Math.min(Math.max(generation,previous?.generation||1),10);const health=inactive&&age>=thresholds.extinctionDays?0:Math.min(98,Math.max(3,Math.round(35+(1-drawdown)*40+Math.min(ratio,.5)*35+Math.min(holders/1000,20)-Math.max(drawdown-.8,0)*120)));
 const traits=[];if(holders>=thresholds.socialHolders)traits.push('SOCIAL');if(ratio>=thresholds.metabolismRatio)traits.push('HIGH METABOLISM');if(drawdown>=thresholds.mutationDrawdown)traits.push('SCARRED','VOLATILE');if(age>=thresholds.ancientDays)traits.push('ANCIENT');if(ratio<thresholds.dormantRatio)traits.push('DORMANT');if(previous&&previous.marketCap<mc&&previous.marketCap<previous.athMarketCap*.35)traits.push('SURVIVOR');if(health<thresholds.criticalHealth)traits.push('FRAGILE');if(!traits.length)traits.push('GENESIS');
 let status=health===0?'EXTINCT':health<thresholds.criticalHealth?'CRITICAL':ratio<thresholds.dormantRatio?'DORMANT':drawdown>.65?'MUTATING':'THRIVING';if(previous?.status==='EXTINCT'&&volume>0){status='RESURRECTED';traits.unshift('REFUSES TO DIE');}else if(traits.includes('SURVIVOR'))status='SURVIVOR';
 const target=thresholds.generations[generation]||mc*2,base=thresholds.generations[generation-1];const progress=Math.min(99,Math.max(0,Math.round((mc-base)/(target-base)*100)));
 const roots=['Canis','Felis','Vapor','Rana','Sciurus','Capra'];const suffixes=['Volatilis','Solanus','Memeticus','Ferratus','Apertus','Resurgens'];const scientificName=roots[seed%6]+' '+input.ticker.charAt(0).toUpperCase()+input.ticker.slice(1).toLowerCase()+'us '+suffixes[(seed>>>8)%6];const id='custom-'+S.hash(input.contractAddress.trim().toLowerCase()).toString(36);const speciesImage=`assets/species/${['bonk','popcat','fartcoin','brett','pnut','goat'][seed%6]}.svg`;const now=new Date().toISOString();
 const history=previous?previous.evolutionHistory.slice():Array.from({length:generation},(_,g)=>({date:new Date(Date.parse(now)-age*864e5*(generation-g)/generation).toISOString().slice(0,10),marketCap:Math.round(Math.max(1000,thresholds.generations[g])),event:g===0?'BIRTH':`GEN ${S.roman(g+1)}`,trait:traits[g%traits.length],form:g+1,image:speciesImage}));
 let event=null;if(previous){if(status==='RESURRECTED')event='RESURRECTION';else if(mc>previous.athMarketCap)event='NEW ATH';else if(mc<=previous.marketCap*(1-thresholds.mutationDrawdown))event='MUTATION';else if(generation>previous.generation)event='EVOLUTION';else if(status==='EXTINCT'&&previous.status!=='EXTINCT')event='EXTINCTION';else if(status==='SURVIVOR')event='SURVIVAL';if(event)history.push({date:now.slice(0,10),marketCap:mc,event,trait:traits[0],form:generation,image:speciesImage});}
 return {...input,id,number:1000+seed%89000,tokenName:input.tokenName.trim(),ticker:input.ticker.trim().toUpperCase().replace(/^\$/,''),contractAddress:input.contractAddress.trim(),speciesName:scientificName,scientificName,originalImage:input.originalImage||speciesImage,speciesImage,marketCap:mc,athMarketCap:ath,volume24h:volume,holders,age,generation,health,status,rarity:['COMMON','RARE','EPIC','LEGENDARY'][seed%4],primaryTrait:traits[0],secondaryTraits:traits,mutationCount:(previous?.mutationCount||Math.floor(drawdown*6)+(seed%3))+(event==='MUTATION'?1:0),extinctionEventsSurvived:(previous?.extinctionEventsSurvived||Math.floor(drawdown*3))+(status==='SURVIVOR'&&previous?.status!=='SURVIVOR'?1:0),evolutionProgress:progress,nextEvolutionRequirement:target,discoveredAt:previous?.discoveredAt||now,evolutionHistory:history,marketHistory:previous?[...previous.marketHistory,mc].slice(-40):[mc*.15,mc*.4,ath,mc],description:input.description||`A market-born ${roots[seed%6].toLowerCase()} organism. Its ${traits[0].toLowerCase()} DNA is shaped by population, activity and drawdowns. Every scar is a record of survival.`,demo:false,born:previous?.born||new Date(Date.parse(now)-age*864e5).toISOString().slice(0,10),extinctAt:status==='EXTINCT'?now.slice(0,10):null,causeOfDeath:'NO SIGNS OF LIFE',lifetimeVolume:(previous?.lifetimeVolume||0)+volume,event};
 },simulate(species,kind){const changes={pump:{marketCap:Math.max(species.marketCap*1.8,species.nextEvolutionRequirement*1.04),volume24h:Math.max(species.volume24h*2,species.marketCap*.3),holders:Math.round(species.holders*1.2)},crash:{marketCap:species.marketCap*.18,volume24h:species.marketCap*.35},dormant:{volume24h:0,age:Math.max(14,species.age)},revive:{marketCap:Math.max(150000,species.marketCap*30),volume24h:50000,holders:Math.max(1600,species.holders)}};const next=this.analyze({...species,...changes[kind]},species);return {...next,id:species.id,number:species.number,demo:species.demo,scientificName:species.scientificName,speciesName:species.speciesName,speciesImage:species.speciesImage,customArt:species.customArt,evolutionHistory:next.evolutionHistory.map(ev=>({...ev,image:species.customArt?null:species.speciesImage}))};}};
})(window.SpeciesApp);
