/* A low-poly containment habitat: cell membranes, a DNA double helix and market pulses. */
(function(S){
 S.scene={dispose:null,mount(container){this.dispose?.();if(!container||!window.THREE)return;const T=window.THREE;let renderer;try{renderer=new T.WebGLRenderer({alpha:true,antialias:innerWidth>760,powerPreference:'low-power'});}catch{return;}const mobile=innerWidth<760;renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1:1.6));renderer.setSize(container.clientWidth,container.clientHeight);container.prepend(renderer.domElement);const scene=new T.Scene(),camera=new T.PerspectiveCamera(40,container.clientWidth/container.clientHeight,.1,100);camera.position.set(0,0,10);const habitat=new T.Group();scene.add(habitat);
 const membranes=new T.MeshBasicMaterial({color:0x8aaa58,wireframe:true,transparent:true,opacity:.08});const cellGeo=new T.IcosahedronGeometry(1,1);for(let i=0;i<(mobile?5:10);i++){const cell=new T.Mesh(cellGeo,membranes);cell.position.set(Math.sin(i*2.4)*4,Math.cos(i*1.7)*3,-2-i*.3);cell.scale.setScalar(.22+(i%3)*.19);habitat.add(cell);}
 const helix=new T.Group();helix.position.set(1.4,0,-3);helix.rotation.z=-.3;habitat.add(helix);const strands=[[],[]];const count=mobile?28:46;for(let i=0;i<count;i++){const y=i/count*7-3.5,a=i*.42;for(let k=0;k<2;k++)strands[k].push(new T.Vector3(Math.cos(a+k*Math.PI)*.75,y,Math.sin(a+k*Math.PI)*.75));if(i%2===0){const geometry=new T.BufferGeometry().setFromPoints([strands[0][i],strands[1][i]]);helix.add(new T.Line(geometry,new T.LineBasicMaterial({color:0xb4d776,transparent:true,opacity:.13})));}}
 strands.forEach(points=>helix.add(new T.Line(new T.BufferGeometry().setFromPoints(points),new T.LineBasicMaterial({color:0xc1f55a,transparent:true,opacity:.2}))));
 const pulse=new T.Mesh(new T.SphereGeometry(.045,6,6),new T.MeshBasicMaterial({color:0xc1f55a,transparent:true,opacity:.65}));helix.add(pulse);
 const rings=new T.Group();habitat.add(rings);for(let i=0;i<3;i++){const ring=new T.Mesh(new T.TorusGeometry(2.3+i*.3,.005,3,mobile?70:120),new T.MeshBasicMaterial({color:0x889d60,transparent:true,opacity:.11}));ring.rotation.x=.3+i*.22;ring.rotation.y=i*.17;rings.add(ring);}
 const pointer={x:0,y:0};const move=ev=>{pointer.x=(ev.clientX/innerWidth-.5)*.2;pointer.y=(ev.clientY/innerHeight-.5)*.1;};window.addEventListener('pointermove',move,{passive:true});const observer=new ResizeObserver(()=>{if(!container.clientWidth)return;renderer.setSize(container.clientWidth,container.clientHeight);camera.aspect=container.clientWidth/container.clientHeight;camera.updateProjectionMatrix();});observer.observe(container);let frame,active=true;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const draw=time=>{if(!active)return;if(!document.hidden){const t=time*.00015;habitat.rotation.y+=(pointer.x-habitat.rotation.y)*.018;habitat.rotation.x+=(pointer.y-habitat.rotation.x)*.018;helix.rotation.y=reduced?0:t*.45;rings.rotation.z=reduced?0:t*.04;const i=Math.floor((time*.003)%count);pulse.position.copy(strands[0][i]);habitat.children.slice(0,mobile?5:10).forEach((c,j)=>{c.rotation.y=reduced?0:t*(j%2?1:-1);});renderer.render(scene,camera);}frame=requestAnimationFrame(draw);};frame=requestAnimationFrame(draw);this.dispose=()=>{active=false;cancelAnimationFrame(frame);observer.disconnect();window.removeEventListener('pointermove',move);scene.traverse(o=>{o.geometry?.dispose();if(o.material)for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose();});renderer.dispose();renderer.domElement.remove();this.dispose=null;};}
 };
})(window.SpeciesApp);
